"""date created and modified is added to the table

Revision ID: 1457a4f0bab0
Revises: e3d0dd4bb145
Create Date: 2025-07-13 05:47:30.311657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1457a4f0bab0'
down_revision: Union[str, Sequence[str], None] = 'e3d0dd4bb145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'date_modified')
    op.drop_column('products', 'date_created')
    # ### end Alembic commands ###
