"""added the whatsapp_message_id

Revision ID: 3fffea2d091c
Revises: 703416ae2287
Create Date: 2025-07-28 13:36:17.267252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fffea2d091c'
down_revision: Union[str, Sequence[str], None] = '703416ae2287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_messages', sa.Column('whatsapp_message_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'whatsapp_messages', ['whatsapp_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_messages', type_='unique')
    op.drop_column('whatsapp_messages', 'whatsapp_message_id')
    # ### end Alembic commands ###
