"""order table is changed

Revision ID: 432462cab48d
Revises: 1457a4f0bab0
Create Date: 2025-07-21 07:45:43.857872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432462cab48d'
down_revision: Union[str, Sequence[str], None] = '1457a4f0bab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('attribution_referrer', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('session_pages', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('session_count', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('device_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'device_type')
    op.drop_column('orders', 'session_count')
    op.drop_column('orders', 'session_pages')
    op.drop_column('orders', 'attribution_referrer')
    # ### end Alembic commands ###
