"""added the status field to the model whatsappmessage

Revision ID: 703416ae2287
Revises: de11b3ffb8b9
Create Date: 2025-07-28 12:56:32.286067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703416ae2287'
down_revision: Union[str, Sequence[str], None] = 'de11b3ffb8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_messages', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_messages', 'status')
    # ### end Alembic commands ###
